### ISSUE TITLE
Installing “jupyter-notebook@0.0.6” failed.

### ISSUE THREAD

**Issue by dmdsig** [jupyter/atom-notebook#23]
Windows 10 up to date with
latest Atom fresh install with fresh Anaconda 3.5 install:

> runas@3.1.1 install C:\Users\KROENEN\AppData\Local\Temp\apm-install-dir-1151115-20820-p01maq\node_modules\jupyter-notebook\node_modules\pathwatcher\node_modules\runas
> node-gyp rebuild

C:\Users\KROENEN\AppData\Local\Temp\apm-install-dir-1151115-20820-p01maq\node_modules\jupyter-notebook\node_modules\pathwatcher\node_modules\runas>if not defined npm_config_node_gyp (node "C:\Users\KROENEN\AppData\Local\atom\app-1.3.1\resources\app\apm\node_modules\npm\bin\node-gyp-bin\\..\..\node_modules\node-gyp\bin\node-gyp.js" rebuild )  else (node  rebuild ) 

> jupyter-js-services@0.2.2 postinstall C:\Users\KROENEN\AppData\Local\Temp\apm-install-dir-1151115-20820-p01maq\node_modules\jupyter-notebook\node_modules\jupyter-js-services
> npm dedupe

> utf-8-validate@1.2.1 install C:\Users\KROENEN\AppData\Local\Temp\apm-install-dir-1151115-20820-p01maq\node_modules\jupyter-notebook\node_modules\ws\node_modules\utf-8-validate
> node-gyp rebuild

C:\Users\KROENEN\AppData\Local\Temp\apm-install-dir-1151115-20820-p01maq\node_modules\jupyter-notebook\node_modules\ws\node_modules\utf-8-validate>if not defined npm_config_node_gyp (node "C:\Users\KROENEN\AppData\Local\atom\app-1.3.1\resources\app\apm\node_modules\npm\bin\node-gyp-bin\\..\..\node_modules\node-gyp\bin\node-gyp.js" rebuild )  else (node  rebuild ) 

> bufferutil@1.2.1 install C:\Users\KROENEN\AppData\Local\Temp\apm-install-dir-1151115-20820-p01maq\node_modules\jupyter-notebook\node_modules\ws\node_modules\bufferutil
> node-gyp rebuild

C:\Users\KROENEN\AppData\Local\Temp\apm-install-dir-1151115-20820-p01maq\node_modules\jupyter-notebook\node_modules\ws\node_modules\bufferutil>if not defined npm_config_node_gyp (node "C:\Users\KROENEN\AppData\Local\atom\app-1.3.1\resources\app\apm\node_modules\npm\bin\node-gyp-bin\\..\..\node_modules\node-gyp\bin\node-gyp.js" rebuild )  else (node  rebuild ) 

gypgypgypnpm WARN optional dep failed, continuing utf-8-validate@1.2.1
npm WARN optional dep failed, continuing bufferutil@1.2.1
npm ERR! Windows_NT 6.2.9200
npm ERR! argv "C:\\Users\\KROENEN\\AppData\\Local\\atom\\app-1.3.1\\resources\\app\\apm\\bin\\node.exe" "C:\\Users\\KROENEN\\AppData\\Local\\atom\\app-1.3.1\\resources\\app\\apm\\node_modules\\npm\\bin\\npm-cli.js" "--globalconfig" "C:\\Users\\KROENEN\\.atom\\.apm\\.apmrc" "--userconfig" "C:\\Users\\KROENEN\\.atom\\.apmrc" "install" "C:\\Users\\KROENEN\\AppData\\Local\\Temp\\d-1151115-20820-kjxvde\\package.tgz" "--target=0.34.3" "--arch=ia32"
npm ERR! node v0.10.40
npm ERR! npm  v2.13.3
npm ERR! code ELIFECYCLE

npm ERR! runas@3.1.1 install: `node-gyp rebuild`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the runas@3.1.1 install script 'node-gyp rebuild'.
npm ERR! This is most likely a problem with the runas package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node-gyp rebuild
npm ERR! You can get their info via:
npm ERR!     npm owner ls runas
npm ERR! There is likely additional logging output above.

**Comment by gnestor** [comment]
Try upgrading to Node 4.2.3 and reinstalling. This package uses a version of pathwatcher that requires node-runas that is intended to build on Node >=4. Atom >=1.2 uses Node 4.

**Comment by gnestor** [comment]
Similar https://github.com/jupyter/atom-notebook/issues/14

**Comment by dmdsig** [comment]
Did as you said and I'm getting the same error message, running everything as admin.

![image](https://cloud.githubusercontent.com/assets/16315469/11878904/f3656db8-a4bd-11e5-901c-becefdab1ff2.png)
I think ATOM is not recognizing the install of the new npm and Node even though I uninstalled atom, restarted computer and reinstalled it.

![image](https://cloud.githubusercontent.com/assets/16315469/11878956/378480f6-a4be-11e5-9d46-6e82008a5dba.png)

**Comment by gnestor** [comment]
`apm -v` is returning the following for me:

apm  1.4.1
npm  2.13.3
node 0.10.40
python 2.7.10
git 2.5.4

I'm not sure if there's any difference, but have you tried installing
inside Atom vs. `apm install jupyter-notebook`?

**Comment by dmdsig** [comment]
Yes I just tried it manually:

C:\Users\KROENEN>apm install jupyter-notebook
Installing jupyter-notebook to C:\Users\KROENEN\.atom\packages failed

> jupyter-js-services@0.2.2 postinstall C:\Users\KROENEN\AppData\Local\Temp\apm-install-dir-1151119-9244-lveqe0\node_modules\jupyter-notebook\node_modules\jupyter-js-services
> npm dedupe


> runas@3.1.1 install C:\Users\KROENEN\AppData\Local\Temp\apm-install-dir-1151119-9244-lveqe0\node_modules\jupyter-notebook\node_modules\pathwatcher\node_modules\runas
> node-gyp rebuild


C:\Users\KROENEN\AppData\Local\Temp\apm-install-dir-1151119-9244-lveqe0\node_modules\jupyter-notebook\node_modules\pathwatcher\node_modules\runas>if not defined npm_config_node_gyp (node "C:\Users\KROENEN\AppData\Local\atom\app-1.3.2\resources\app\apm\node_modules\npm\bin\node-gyp-bin\\..\..\node_modules\node-gyp\bin\node-gyp.js" rebuild )  else (node  rebuild )

> bufferutil@1.2.1 install C:\Users\KROENEN\AppData\Local\Temp\apm-install-dir-1151119-9244-lveqe0\node_modules\jupyter-notebook\node_modules\ws\node_modules\bufferutil
> node-gyp rebuild


C:\Users\KROENEN\AppData\Local\Temp\apm-install-dir-1151119-9244-lveqe0\node_modules\jupyter-notebook\node_modules\ws\node_modules\bufferutil>if not defined npm_config_node_gyp (node "C:\Users\KROENEN\AppData\Local\atom\app-1.3.2\resources\app\apm\node_modules\npm\bin\node-gyp-bin\\..\..\node_modules\node-gyp\bin\node-gyp.js" rebuild )  else (node  rebuild )

> utf-8-validate@1.2.1 install C:\Users\KROENEN\AppData\Local\Temp\apm-install-dir-1151119-9244-lveqe0\node_modules\jupyter-notebook\node_modules\ws\node_modules\utf-8-validate
> node-gyp rebuild


C:\Users\KROENEN\AppData\Local\Temp\apm-install-dir-1151119-9244-lveqe0\node_modules\jupyter-notebook\node_modules\ws\node_modules\utf-8-validate>if not defined npm_config_node_gyp (node "C:\Users\KROENEN\AppData\Local\atom\app-1.3.2\resources\app\apm\node_modules\npm\bin\node-gyp-bin\\..\..\node_modules\node-gyp\bin\node-gyp.js" rebuild )  else (node  rebuild )

gypgypgypnpm WARN optional dep failed, continuing bufferutil@1.2.1
npm WARN optional dep failed, continuing utf-8-validate@1.2.1
npm ERR! Windows_NT 6.2.9200
npm ERR! argv "C:\\Users\\KROENEN\\AppData\\Local\\atom\\app-1.3.2\\resources\\app\\apm\\bin\\node.exe" "C:\\Users\\KROENEN\\AppData\\Local\\atom\\app-1.3.2\\resources\\app\\apm\\node_modules\\npm\\bin\\npm-cli.js" "--globalconfig" "C:\\Users\\KROENEN\\.atom\\.apm\\.apmrc" "--userconfig" "C:\\Users\\KROENEN\\.atom\\.apmrc" "install" "C:\\Users\\KROENEN\\AppData\\Local\\Temp\\d-1151119-9244-9s5eh8\\package.tgz" "--target=0.34.3" "--arch=ia32"
npm ERR! node v0.10.40
npm ERR! npm  v2.13.3
npm ERR! code ELIFECYCLE

npm ERR! runas@3.1.1 install: `node-gyp rebuild`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the runas@3.1.1 install script 'node-gyp rebuild'.
npm ERR! This is most likely a problem with the runas package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node-gyp rebuild
npm ERR! You can get their info via:
npm ERR!     npm owner ls runas
npm ERR! There is likely additional logging output above.

I don't know what to do.

**Comment by gnestor** [comment]
I'm not sure either. You could try to clone the repo and `npm install && npm link` (as this should use your 4.2.3 version of Node vs. Atom's 0.10.40 version).

**Comment by dmdsig** [comment]
I'm sorry but I don't think I understand what you told me very well, could you elaborate upon it?

**Comment by gnestor** [comment]
See https://github.com/jupyter/atom-notebook#developers

In terminal:
```bash
git clone https://github.com/jupyter/atom-notebook.git
cd atom-notebook
npm install
npm link
```

This will allow you to link the jupyter-notebook Atom package to this development directory so that you can contribute to the source code and test it in Atom. Installing it this way should use your user/system version of Node (4.2.3) and NPM which should solve the problem.

**Comment by fonnesbeck** [comment]
I'm getting a similar error, and building from the cloned repo does not seem to solve it. [Here is the debug log](http://dsh.re/85034). 

APM setup is:

```
apm  1.4.1
npm  2.13.3
node 0.10.40
python 3.5.1
git 2.5.0
```

**Comment by fonnesbeck** [comment]
I seem to have 2 node-gyp packages installed. The install process reports 3.0.3, but when I run `node-gyp -v`, I get 3.2.1.

**Comment by crucialfelix** [comment]
Same failure here. Atom currently uses node 0.10.40 and we don't have any choice in that.  (why is it so far behind ? that's surprising)

While it may be possible to clone and install with a different node (and thus succeed in building it) we can't just install the package using Atom.

```
> runas@3.1.1 install /private/var/folders/7q/1q7s2z114_l479ntqd0t93s00000gn/T/apm-install-dir-1151131-16882-1ee3mbb/node_modules/jupyter-notebook/node_modules/pathwatcher/node_modules/runas
> node-gyp rebuild

  CXX(target) Release/obj.target/runas/src/main.o
  CXX(target) Release/obj.target/runas/src/runas_darwin.o
  CXX(target) Release/obj.target/runas/src/fork.o
  SOLINK_MODULE(target) Release/runas.node

> bufferutil@1.2.1 install /private/var/folders/7q/1q7s2z114_l479ntqd0t93s00000gn/T/apm-install-dir-1151131-16882-1ee3mbb/node_modules/jupyter-notebook/node_modules/ws/node_modules/bufferutil
> node-gyp rebuild

  CXX(target) Release/obj.target/bufferutil/src/bufferutil.o
  SOLINK_MODULE(target) Release/bufferutil.node

> utf-8-validate@1.2.1 install /private/var/folders/7q/1q7s2z114_l479ntqd0t93s00000gn/T/apm-install-dir-1151131-16882-1ee3mbb/node_modules/jupyter-notebook/node_modules/ws/node_modules/utf-8-validate
> node-gyp rebuild

  CXX(target) Release/obj.target/validation/src/validation.o
  SOLINK_MODULE(target) Release/validation.node

> jupyter-js-services@0.2.2 postinstall /private/var/folders/7q/1q7s2z114_l479ntqd0t93s00000gn/T/apm-install-dir-1151131-16882-1ee3mbb/node_modules/jupyter-notebook/node_modules/jupyter-js-services
> npm dedupe


> pathwatcher@6.3.0 install /private/var/folders/7q/1q7s2z114_l479ntqd0t93s00000gn/T/apm-install-dir-1151131-16882-1ee3mbb/node_modules/jupyter-notebook/node_modules/pathwatcher
> node-gyp rebuild

  CXX(target) Release/obj.target/pathwatcher/src/main.o
  CXX(target) Release/obj.target/pathwatcher/src/common.o
  CXX(target) Release/obj.target/pathwatcher/src/handle_map.o
  CXX(target) Release/obj.target/pathwatcher/src/pathwatcher_unix.o
  SOLINK_MODULE(target) Release/pathwatcher.node

2015-12-31 14:10:43.414 xcodebuild[16891:381141] [MT] PluginLoading: Required plug-in compatibility UUID 7265231C-39B4-402C-89E1-16167C4CC990 for plug-in at path '~/Library/Application Support/Developer/Shared/Xcode/Plug-ins/OMColorSense.xcplugin' not present in DVTPlugInCompatibilityUUIDs
2015-12-31 14:10:43.416 xcodebuild[16891:381141] [MT] PluginLoading: Required plug-in compatibility UUID 7265231C-39B4-402C-89E1-16167C4CC990 for plug-in at path '~/Library/Application Support/Developer/Shared/Xcode/Plug-ins/OFPlugin.xcplugin' not present in DVTPlugInCompatibilityUUIDs
2015-12-31 14:10:43.418 xcodebuild[16891:381141] [MT] PluginLoading: Required plug-in compatibility UUID 7265231C-39B4-402C-89E1-16167C4CC990 for plug-in at path '~/Library/Application Support/Developer/Shared/Xcode/Plug-ins/CocoaPods.xcplugin' not present in DVTPlugInCompatibilityUUIDs
2015-12-31 14:10:47.299 xcodebuild[17053:381458] [MT] PluginLoading: Required plug-in compatibility UUID 7265231C-39B4-402C-89E1-16167C4CC990 for plug-in at path '~/Library/Application Support/Developer/Shared/Xcode/Plug-ins/OMColorSense.xcplugin' not present in DVTPlugInCompatibilityUUIDs
2015-12-31 14:10:47.300 xcodebuild[17053:381458] [MT] PluginLoading: Required plug-in compatibility UUID 7265231C-39B4-402C-89E1-16167C4CC990 for plug-in at path '~/Library/Application Support/Developer/Shared/Xcode/Plug-ins/OFPlugin.xcplugin' not present in DVTPlugInCompatibilityUUIDs
2015-12-31 14:10:47.301 xcodebuild[17053:381458] [MT] PluginLoading: Required plug-in compatibility UUID 7265231C-39B4-402C-89E1-16167C4CC990 for plug-in at path '~/Library/Application Support/Developer/Shared/Xcode/Plug-ins/CocoaPods.xcplugin' not present in DVTPlugInCompatibilityUUIDs
2015-12-31 14:10:48.869 xcodebuild[17123:381566] [MT] PluginLoading: Required plug-in compatibility UUID 7265231C-39B4-402C-89E1-16167C4CC990 for plug-in at path '~/Library/Application Support/Developer/Shared/Xcode/Plug-ins/OMColorSense.xcplugin' not present in DVTPlugInCompatibilityUUIDs
2015-12-31 14:10:48.870 xcodebuild[17123:381566] [MT] PluginLoading: Required plug-in compatibility UUID 7265231C-39B4-402C-89E1-16167C4CC990 for plug-in at path '~/Library/Application Support/Developer/Shared/Xcode/Plug-ins/OFPlugin.xcplugin' not present in DVTPlugInCompatibilityUUIDs
2015-12-31 14:10:48.871 xcodebuild[17123:381566] [MT] PluginLoading: Required plug-in compatibility UUID 7265231C-39B4-402C-89E1-16167C4CC990 for plug-in at path '~/Library/Application Support/Developer/Shared/Xcode/Plug-ins/CocoaPods.xcplugin' not present in DVTPlugInCompatibilityUUIDs
sh: npm: command not found
2015-12-31 14:10:50.492 xcodebuild[17194:381683] [MT] PluginLoading: Required plug-in compatibility UUID 7265231C-39B4-402C-89E1-16167C4CC990 for plug-in at path '~/Library/Application Support/Developer/Shared/Xcode/Plug-ins/OMColorSense.xcplugin' not present in DVTPlugInCompatibilityUUIDs
2015-12-31 14:10:50.494 xcodebuild[17194:381683] [MT] PluginLoading: Required plug-in compatibility UUID 7265231C-39B4-402C-89E1-16167C4CC990 for plug-in at path '~/Library/Application Support/Developer/Shared/Xcode/Plug-ins/OFPlugin.xcplugin' not present in DVTPlugInCompatibilityUUIDs
2015-12-31 14:10:50.495 xcodebuild[17194:381683] [MT] PluginLoading: Required plug-in compatibility UUID 7265231C-39B4-402C-89E1-16167C4CC990 for plug-in at path '~/Library/Application Support/Developer/Shared/Xcode/Plug-ins/CocoaPods.xcplugin' not present in DVTPlugInCompatibilityUUIDs
npm ERR! Darwin 14.5.0
npm ERR! argv "/Applications/Atom.app/Contents/Resources/app/apm/bin/node" "/Applications/Atom.app/Contents/Resources/app/apm/node_modules/npm/bin/npm-cli.js" "--globalconfig" "/Users/crucial/.atom/.apm/.apmrc" "--userconfig" "/Users/crucial/.atom/.apmrc" "install" "/private/var/folders/7q/1q7s2z114_l479ntqd0t93s00000gn/T/d-1151131-16882-1p0zodz/package.tgz" "--target=0.34.3" "--arch=x64"
npm ERR! node v0.10.40
npm ERR! npm  v2.13.3
npm ERR! file sh
npm ERR! code ELIFECYCLE
npm ERR! errno ENOENT
npm ERR! syscall spawn

npm ERR! jupyter-js-services@0.2.2 postinstall: `npm dedupe`
npm ERR! spawn ENOENT
npm ERR! 
npm ERR! Failed at the jupyter-js-services@0.2.2 postinstall script 'npm dedupe'.
npm ERR! This is most likely a problem with the jupyter-js-services package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     npm dedupe
npm ERR! You can get their info via:
npm ERR!     npm owner ls jupyter-js-services
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /private/var/folders/7q/1q7s2z114_l479ntqd0t93s00000gn/T/apm-install-dir-1151131-16882-1ee3mbb/npm-debug.log
```

**Comment by rgbkrk** [comment]
`node-gyp` is forceably dependent on Python2.

Couple things to try:

```
apm --python /usr/bin/python2.7 install
```

What I do on my system is set which python `npm` uses:

```
npm config set python /path/to/executable/python2.7
```

Though I'm not sure if that setting applies to the bundled npm that comes with Atom.

**Comment by fonnesbeck** [comment]
Unfortunately, neither the `--python` switch for apm nor `npm config` seems to do the trick. It still tries to use 3.5:

    gyp ERR! stack Error: Python executable "python" is v3.5.1, which is not supported by gyp.

I have confirmed that /usr/bin/python2.7 exists.

**Comment by rgbkrk** [comment]
I wonder if we can rely on anything from https://github.com/nodejs/node-gyp/pull/502 or if upgrading node-gyp helps.

**Comment by gnestor** [comment]
@fonnesbeck Did you clone and install using `npm install` or `apm install`? `npm install` will use the user's version of Node vs. Node 0.10.40.

**Comment by gnestor** [comment]
@fonnesbeck If that doesn't fix it, try `PYTHON=python2 apm install`. 

Reference: https://github.com/atom/node-oniguruma/issues/18#issuecomment-50021909

**Comment by gnestor** [comment]
Related: https://github.com/willwhitney/hydrogen/issues/12

**Comment by crucialfelix** [comment]
check `which python` on your command line.  that is the one that will be
used. I had installed some things using conda and accidentally shadowed my
old python with a new 3.5.1 install.

I just moved it / renamed it and then the old default 2.7.3 was the "first
hit" in paths and node-gyp could install jupyter-notebook.

**Comment by gnestor** [comment]
@fonnesbeck Were you able to resolve this?

**Comment by fonnesbeck** [comment]
My machine is in the shop. Should be able to try it out by the end of the week.

**Comment by gnestor** [comment]
@fonnesbeck Looks like you were able to install? https://github.com/jupyter/atom-notebook/issues/29

Did `PYTHON=python2 apm install` resolve it for you?

**Comment by fonnesbeck** [comment]
Correct. Setting PYTHON at the install command worked. Now suffering from #29
